### ISSUE TITLE
[Develop] MAPBOX_API_KEY is not present on deployment

### ISSUE THREAD

**Issue by StephanieHou** [gcivil-nyu-org/INET-Monday-Spring2023-Team-5#102] opened 2023-04-05 03:00 UTC
Hi Venu! 

I merged styling into develop after checking everything was working properly with the export instructions you provided.
After testing dev site, it is showing the error "MAPBOX_API_KEY not found. Declare it as envvar or define a default value." when clicking to go to the neighborhoods page. Seems that the key set isn't working.

**Comment by vchrombie** [comment] 2023-04-05 04:30
HI @StephanieHou, the issue is known. I didn't setup the `MAPBOX_API_KEY` as an env variable in the production environment. I was thinking to do it right before we merge your PR with the mapbox integration.

But, I guess we merged it so let me go and add it.

**Comment by vchrombie** [comment] 2023-04-05 04:33
There you go! I have added the env variables. Mapbox is working fine.

**Closed by vchrombie** 2023-04-05 04:33 UTC
